<img src = "https://img.betapage.co/images/77640967-77641456.png" height=50% width = 50%>

In [1]:
import numpy as np

# Introduction to NumPy

"Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. This library provides you with an array data structure that holds some benefits over Python lists, such as: being more compact, faster access in reading and writing items, being more convenient and more efficient."


# What is a NumPy array?

"The central feature of NumPy is the array object class. Arrays are similar to lists in Python, except that every element of an array must be of the same type, typically a numeric type like float or int. Arrays make operations with large amounts of numeric data very fast and are generally much more efficient than lists."

LINK: https://engineering.ucsb.edu/~shell/che210d/numpy.pdf

<img src = "http://community.datacamp.com.s3.amazonaws.com/community/production/ckeditor_assets/pictures/332/content_arrays-axes.png">

# NumPy Array Syntax
The function array takes two arguments: the list to be converted into the array and the type of each member of the list. 

In [2]:
#List to be converted
lst = [1,2,3,4,5,6,7,8,9]

arr = np.array(lst)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Array elements are accessed, sliced, and manipulated just like lists.

In [3]:
#Index from the 2nd index on
arr[2:]

array([3, 4, 5, 6, 7, 8, 9])

In [4]:
#manipulate item at index 0
arr[0] = 10
arr

array([10,  2,  3,  4,  5,  6,  7,  8,  9])


<b>* Why can't we simply use a python list for these scientific computations?<b>

# Python List VS NumPy Array

"Arrays and lists are both used in Python to store data, but they don't serve exactly the same purposes. They both can be used to store any data type (real numbers, strings, etc), and they both can be indexed and iterated through, but the similarities between the two don't go much further. The main difference between a list and an array is the functions that you can perform to them. For example, you can divide an array by 3, and each number in the array will be divided by 3 and the result will be printed if you request it. If you try to divide a list by 3, Python will tell you that it can't be done, and an error will be thrown."


In [5]:
lst = [3,6,9,12,15,18,12]
lst/3

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [6]:
arr = np.array([3,6,9,12,15,18,12])
arr/3

array([1., 2., 3., 4., 5., 6., 4.])

Arrays can be multidimensional. Unlike lists, different axes are accessed using commas inside bracket notation. Here is an example with a two-dimensional array (e.g., a matrix)

In [7]:
lst1 = [1,2,3,4,5]
lst2 = [5,6,7,8,9]
arr = np.array([lst1,lst2])
arr

array([[1, 2, 3, 4, 5],
       [5, 6, 7, 8, 9]])

In [8]:
arr/3

array([[0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667],
       [1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ]])

In [9]:
lst_lst = [lst1,lst2]
lst_lst

[[1, 2, 3, 4, 5], [5, 6, 7, 8, 9]]

In [10]:
lst_lst/3

TypeError: unsupported operand type(s) for /: 'list' and 'int'

# Indexing Arrays VS Lists

In [11]:
arr

array([[1, 2, 3, 4, 5],
       [5, 6, 7, 8, 9]])

In [12]:
arr[0][1]

2

In [13]:
lst_lst

[[1, 2, 3, 4, 5], [5, 6, 7, 8, 9]]

In [14]:
lst_lst[0,1]

TypeError: list indices must be integers or slices, not tuple

In [15]:
lst_lst[0][1]

2

In [16]:
arr[-1]

array([5, 6, 7, 8, 9])

In [17]:
lst_lst[-1]

[5, 6, 7, 8, 9]

In [18]:
arr

array([[1, 2, 3, 4, 5],
       [5, 6, 7, 8, 9]])

<h3> How to index a multidemsional array? </h3><br>
The individual elements of arrays can be accessed in the same way as for lists.

<img src = "http://www.scipy-lectures.org/_images/numpy_indexing.png" height = 60% width = 60%>

In [19]:
list_2d = [[0,1,2,3,4,5],
           [10,11,12,13,14,15],
           [20,21,22,23,24,25],
           [30,31,32,33,34,35],
           [40,41,42,43,44,45],
           [50,51,52,53,54,55]]

In [20]:
array_2d = np.array(list_2d)
print(array_2d)
array_2d.shape

[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]


(6, 6)

In [21]:
print(array_2d[0,3:5])
#start column 3 end before 5

[3 4]


In [22]:
print(array_2d[4:,4:])
#forth row, forth column

[[44 45]
 [54 55]]


In [23]:
print(array_2d[:,2])
#all rows, second column

[ 2 12 22 32 42 52]


In [24]:
print(array_2d[2::2,::2]) # step by 2
#start, stop and skip


[[20 22 24]
 [40 42 44]]


In [25]:
# adding new column to numpy array

In [26]:
calc = array_2d[:,5] * 1.05
new_column = np.array(calc) #convert to array
print(new_column)

[ 5.25 15.75 26.25 36.75 47.25 57.75]


In [27]:
new_array_2d = np.column_stack((array_2d,new_column)) #new stack options vertical, horizontal
print(new_array_2d)

[[ 0.    1.    2.    3.    4.    5.    5.25]
 [10.   11.   12.   13.   14.   15.   15.75]
 [20.   21.   22.   23.   24.   25.   26.25]
 [30.   31.   32.   33.   34.   35.   36.75]
 [40.   41.   42.   43.   44.   45.   47.25]
 [50.   51.   52.   53.   54.   55.   57.75]]


# Changing Array to different DataType

In [28]:
arr = arr.tolist()
arr

[[1, 2, 3, 4, 5], [5, 6, 7, 8, 9]]

In [29]:
type(arr)

list

In [30]:
arr = np.array(arr)
arr

array([[1, 2, 3, 4, 5],
       [5, 6, 7, 8, 9]])

In [31]:
type(arr)

numpy.ndarray

In [32]:
arr.shape

(2, 5)

# Change Array Shape

<img src = "https://www.safaribooksonline.com/library/view/python-for-data/9781449323592/httpatomoreillycomsourceoreillyimages1346880.png" height = 50% width = 30% style = display.left> 

Transposed versions of arrays can also be generated, which will create a new array with the final two axes switched:

In [33]:
arr

array([[1, 2, 3, 4, 5],
       [5, 6, 7, 8, 9]])

In [34]:
arr.shape

(2, 5)

In [35]:
arr.transpose()

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8],
       [5, 9]])

In [36]:
arr.transpose().shape

(5, 2)

In [37]:
arr.reshape((5,2))

array([[1, 2],
       [3, 4],
       [5, 5],
       [6, 7],
       [8, 9]])

Make multidimensional array into one-dimensional array

In [38]:
arr.shape

(2, 5)

In [39]:
arr.flatten()

array([1, 2, 3, 4, 5, 5, 6, 7, 8, 9])

In [40]:
arr.flatten().shape

(10,)

# Create New Array (Specific)

Numpy also provides many functions to create arrays.

Creates an array of all zeros with a specified shape.

In [41]:
#1-Dimensional
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [42]:
#2-Dimensional
np.zeros((2,2), int)

array([[0, 0],
       [0, 0]])

Creates an array of all ones with a specified shape.

In [43]:
#1-Dimensional
np.ones(10, int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [44]:
#2-Dimensional
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

Creates a constant array (specified number) with a specified shape.

In [45]:
#1-Dimensional
np.full(10,7)

array([7, 7, 7, 7, 7, 7, 7, 7, 7, 7])

In [46]:
#2-Dimensional
np.full((2, 2), 7)

array([[7, 7],
       [7, 7]])

Created an array of a specified shape with random values.

In [47]:
#1-Dimensional
np.random.random(10)

array([0.45051064, 0.06382977, 0.24998789, 0.4530747 , 0.77360843,
       0.42817365, 0.4617004 , 0.29187117, 0.96878717, 0.90377117])

In [48]:
#2-Dimensional
np.random.random((2,2))

array([[0.61117196, 0.36554158],
       [0.22781109, 0.53779989]])

Create an array of a specified length with evenly spaced values.

In [49]:
#1-Dimensional
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Create an array with a specified "start", "stop", and number of values, evenly spaced.

In [50]:
#1-Dimensional
np.linspace(1, 10, num = 20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

Creates a 2x2 identity matrix (array).

An identity matrix is a square matrix having 1s on the main diagonal, and 0s everywhere else. These are called identity matrices because, when you multiply them with a compatible matrix , you get back the same matrix.
http://www.sparknotes.com/math/algebra2/matrices/section3.rhtml

In [51]:
#2-Dimensional
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

OR

In [52]:
#2-Dimensional
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

# Math Functions using NumPy

"As such, it probably won’t surprise you that you can just use +, -, *, / or % to add, subtract, multiply, divide or calculate the remainder of two (or more) arrays. However, a big part of why NumPy is so handy, is because it also has functions to do this. The equivalent functions of the operations that you have seen just now are, respectively, np.add(), np.subtract(), np.multiply(), np.divide() and np.remainder()."

https://www.datacamp.com/community/tutorials/python-numpy-tutorial

In [53]:
arr = np.ones((10,10))
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [54]:
np.add(arr,2)

array([[3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.]])

In [55]:
#OR
arr + 2

array([[3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.]])

In [56]:
np.multiply(arr,2)

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.]])

In [57]:
#OR
arr*2

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.]])

In [58]:
np.subtract(arr,1)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [59]:
#OR
arr -1 

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [60]:
np.divide(arr,2)

array([[0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]])

In [61]:
#OR
arr/2

array([[0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]])

In [62]:
np.remainder(arr,1)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [63]:
#OR
arr % 1

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [64]:
arr.sum()

100.0

In [65]:
arr.min()

1.0

In [66]:
arr.max()

1.0

In [67]:
arr.mean()

1.0

# <font color = magenta> NumPy Problem 1 </font>
<font color = magenta>
Create the three arrays displayed in the image, below.

<img src = "https://i.stack.imgur.com/ojnFF.jpg">

In [68]:
arrone = np.array([[4,6,4], [1,1,8], [0,7,5], [5,3,3], [8,9,5]])
arrone

array([[4, 6, 4],
       [1, 1, 8],
       [0, 7, 5],
       [5, 3, 3],
       [8, 9, 5]])

In [69]:
arrtwo = np.array([[8,8,4],[3,4,4], [0,0,9], [3,7,3], [3,4,7]])
arrtwo

array([[8, 8, 4],
       [3, 4, 4],
       [0, 0, 9],
       [3, 7, 3],
       [3, 4, 7]])

In [70]:
arrthree = np.array([[9,5,4], [7,7,3], [9,5,9], [8,7,8], [5,8,8]])
arrthree

array([[9, 5, 4],
       [7, 7, 3],
       [9, 5, 9],
       [8, 7, 8],
       [5, 8, 8]])

# <font color = magenta> NumPy Problem 2 </font>
<font color = magenta>
Create a multidimensional array of your dimension choice and fill it random values(not filled manually).

In [71]:
multiarr = np.random.random((10,10))*3
multiarr

array([[2.03804308, 1.25117654, 0.95239987, 0.14992   , 1.5603475 ,
        1.85686658, 0.23060644, 1.18922004, 1.92872705, 0.36674106],
       [1.81734455, 2.35380165, 2.87206167, 2.85837385, 2.37246935,
        2.25232171, 1.52289635, 2.63130159, 1.63656365, 0.38768995],
       [0.51255714, 2.58388591, 2.01785796, 1.23724457, 0.63484496,
        2.28836538, 0.53823375, 1.85110792, 2.48933459, 1.79066152],
       [1.35458143, 1.39747143, 2.2951251 , 2.75851403, 0.71524532,
        2.09882692, 1.14272819, 2.57993432, 0.7087414 , 1.13480899],
       [2.68721634, 0.25922197, 2.36685079, 0.25841719, 0.18158026,
        0.03065484, 1.65509314, 1.2324295 , 1.13008473, 0.35076505],
       [2.46602585, 0.73981915, 1.73698442, 1.29580581, 2.71424856,
        2.42088648, 1.66963357, 0.50871259, 2.44110148, 0.04491196],
       [2.50852239, 2.80345001, 1.86209637, 2.03502312, 0.28415039,
        2.75856794, 1.7880788 , 0.78204139, 1.11732459, 0.42858295],
       [2.44599095, 0.40290015, 1.0591033

Find the min and max values of your array.

In [72]:
print(multiarr.min())
print(multiarr.max())

0.020259410847391135
2.892644636427637


# <font color = magenta> NumPy Problem 3 </font>
<font color = magenta>
Create another multidimensional array of your dimension choice and fill it random values(not filled manually). Find the max value of your new array and replace it with your min value. Find the min value and replace it in your array with the max value.

In [73]:
multirandom = np.random.randint(0,10,(10,10))
minval = multirandom.min()
maxval = multirandom.max()

print(multirandom)
print(minval)
print(maxval)

for i in range(len(multirandom)):
    for j in range(len(multirandom[i])):
        if multirandom[i][j] == minval:
            multirandom[i][j] = maxval
        elif multirandom[i][j] == maxval:
            multirandom[i][j] = minval
print (multirandom)


[[9 0 0 1 4 5 7 8 6 5]
 [1 6 3 5 0 1 4 7 8 8]
 [4 0 9 9 7 9 5 0 5 0]
 [5 9 1 3 3 3 2 7 0 3]
 [6 6 8 0 5 3 3 3 2 6]
 [9 6 1 5 0 6 7 7 6 3]
 [2 6 4 6 4 6 6 6 7 1]
 [4 5 9 7 8 5 5 6 2 5]
 [6 0 7 9 8 5 2 6 7 1]
 [8 9 2 1 9 4 1 3 2 6]]
0
9
[[0 9 9 1 4 5 7 8 6 5]
 [1 6 3 5 9 1 4 7 8 8]
 [4 9 0 0 7 0 5 9 5 9]
 [5 0 1 3 3 3 2 7 9 3]
 [6 6 8 9 5 3 3 3 2 6]
 [0 6 1 5 9 6 7 7 6 3]
 [2 6 4 6 4 6 6 6 7 1]
 [4 5 0 7 8 5 5 6 2 5]
 [6 9 7 0 8 5 2 6 7 1]
 [8 0 2 1 0 4 1 3 2 6]]


# <font color = magenta> NumPy Problem 4 </font>

Create a random vector of size 10 and sort it.

In [74]:
sorted(np.random.random(10))

[0.06243454240875501,
 0.07195336767382032,
 0.09946895122009425,
 0.12346331961299928,
 0.19391451459382292,
 0.3495712896665163,
 0.38176543272917307,
 0.45239028126683434,
 0.5846374150569984,
 0.6202516113308023]

# <font color = magenta> NumPy Problem 5 </font>

<font color = magenta>
How to swap two rows of an array?

In [75]:
row_swap = 3
arr_1 = np.random.randint(10, size=(6,6))
arr_2 = np.random.randint(10, size=(6,6))
print("Original:")
print(arr_1)
print(arr_2)

row_1 = np.copy(arr_1[row_swap])
row_2 = np.copy(arr_2[row_swap])

arr_1[row_swap] = row_2
arr_2[row_swap] = row_1

print("Modified:")
print(arr_1)
print(arr_2)

Original:
[[7 7 0 3 9 4]
 [4 0 1 5 6 8]
 [6 0 1 1 6 7]
 [0 7 2 0 7 5]
 [7 4 6 5 4 3]
 [4 9 1 9 9 4]]
[[8 8 9 8 4 4]
 [0 3 8 6 4 3]
 [3 1 5 5 0 6]
 [0 7 8 4 9 4]
 [2 3 7 4 6 8]
 [0 9 6 0 6 5]]
Modified:
[[7 7 0 3 9 4]
 [4 0 1 5 6 8]
 [6 0 1 1 6 7]
 [0 7 8 4 9 4]
 [7 4 6 5 4 3]
 [4 9 1 9 9 4]]
[[8 8 9 8 4 4]
 [0 3 8 6 4 3]
 [3 1 5 5 0 6]
 [0 7 2 0 7 5]
 [2 3 7 4 6 8]
 [0 9 6 0 6 5]]


# Numpy with Bay Area housing data set

In [76]:
def read_file_housing(filename): #take the only columns you need.
    file_open = open(filename,"r")
    fixed_file = open("fixed-housing-data.csv","w")
    line_count = 0
    for line in iter(file_open):
        line_count += 1
        if "HomeID" in line:
            continue
        line_no_newline = line.rstrip()
        line1 = line_no_newline.replace("84085","94085") #Ex9
        line2 = line1.replace("84087","94087") #Ex9
        line3 = line2.replace("85014","95014") #Ex9
        line4 = line3.replace("85051","95051") #Ex9
        line5 = line4.replace("l","1") #Ex11 -- Car_Garage
        line_split = line5.split(",")
        if (int(line_split[5]) < 100): #Ex10 -- School_API
            line_split[5] = int(line_split[5]) * 10
        else:
            line_split[5] = int(line_split[5])
        line_split = [str(x) for x in line_split]
        myString = ",".join(line_split) + "\n"
        fixed_file.write(myString) #write a new file.
    return

In [77]:
read_file_housing("bayarea_home_prices.csv")

In [78]:
import numpy as np

In [79]:
"""
0 = HomeID
1 = HomeAge
2 = HomeSqft
3 = LotSize
4 = BedRooms
5 = HighSchoolAPI
6 = ProxFwy
7 = CarGarage
8 = ZipCode
9 = HomePriceK
"""

'\n0 = HomeID\n1 = HomeAge\n2 = HomeSqft\n3 = LotSize\n4 = BedRooms\n5 = HighSchoolAPI\n6 = ProxFwy\n7 = CarGarage\n8 = ZipCode\n9 = HomePriceK\n'

In [80]:
housing = np.loadtxt("fixed-housing-data.csv", #load text file
                          dtype=int, #all data is intergers
                          delimiter=",") #delimited by commas

In [81]:
print(housing[0:2])

[[    1    24  1757  6056     2   899     3     3 94085   894]
 [    2    10  1563  6085     2   959     4     3 94085   861]]


In [82]:
print(housing.shape)

(100, 10)


In [83]:
# home prices
print(housing[:,9])

[ 894  861  831  809  890  867  843  820  874  885  903  912  933  865
  918  950  882  896  942  859  904  912  916  972  908  934  914  949
  919  953  991 1049 1042  994 1030 1019 1044 1038 1024  976 1115 1128
 1071 1059 1000 1185 1015 1114 1138 1068 1068 1097 1074 1114 1075 1130
 1116 1103 1080 1150 1177 1149 1163 1132 1138 1199 1179 1173 1128 1165
 1233 1180 1240 1242 1184 1173 1194 1181 1190 1182 1221 1288 1275 1300
 1272 1294 1219 1282 1256 1205 1252 1294 1269 1335 1267 1307 1336 1284
 1269 1250]


In [84]:
print(housing[:,9] + 10)

[ 904  871  841  819  900  877  853  830  884  895  913  922  943  875
  928  960  892  906  952  869  914  922  926  982  918  944  924  959
  929  963 1001 1059 1052 1004 1040 1029 1054 1048 1034  986 1125 1138
 1081 1069 1010 1195 1025 1124 1148 1078 1078 1107 1084 1124 1085 1140
 1126 1113 1090 1160 1187 1159 1173 1142 1148 1209 1189 1183 1138 1175
 1243 1190 1250 1252 1194 1183 1204 1191 1200 1192 1231 1298 1285 1310
 1282 1304 1229 1292 1266 1215 1262 1304 1279 1345 1277 1317 1346 1294
 1279 1260]


In [85]:
print(housing.sum(axis=0)) # sum by columns

[   5050    1720  161528  784050     271   90443     310     152 9455925
  108099]


In [86]:
print(housing.sum(axis=1)) # sum by rows adding row by row

[103724 103574 103240 103224 103896 103638 104044 103869 103609 104170
 104094 103592 103978 104376 104062 105595 104218 104335 104940 104012
 104075 104583 104684 105583 104958 104446 104876 105593 104503 106006
 105990 106058 106256 105929 106298 105629 106320 106196 106023 106261
 105369 105445 106369 105987 105936 105549 106606 105320 105358 106782
 106365 106479 106225 105461 106713 105795 106138 105594 106827 105847
 105796 106180 105869 105800 106169 107018 106669 106315 106430 106551
 107465 106524 107181 107608 106533 107139 107961 106805 106554 106595
 107843 107864 108077 107983 108182 108227 107735 107879 108478 108106
 107902 108487 107956 108654 108172 108678 108406 108111 108617 108407]


In [88]:
homes_94085 = (housing[:,8] == 94085) #filtering, find homes in this zip, you can add and/or

In [89]:
print(homes_94085)

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True False  True  True False  True  True  True  True False
  True  True  True False  True False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False]


In [90]:
data_94085 = housing[homes_94085,][:,:] #use boolean as index after comma can add additional
print(data_94085)

[[    1    24  1757  6056     2   899     3     3 94085   894]
 [    2    10  1563  6085     2   959     4     3 94085   861]
 [    3    14  1344  6089     2   865     4     3 94085   831]
 [    4    14  1215  6129     3   959     4     2 94085   809]
 [    5    24  1866  6141     3   877     4     1 94085   890]
 [    6    18  1589  6148     2   920     3     0 94085   867]
 [    7    13  1947  6183     3   959     3     1 94085   843]
 [    8    19  1839  6186     3   905     4     0 94085   820]
 [    9    17  1501  6233     2   884     3     1 94085   874]
 [   10    24  1933  6276     2   950     4     1 94085   885]
 [   11    12  1798  6346     3   931     3     2 94085   903]
 [   12    22  1221  6430     3   904     2     1 94085   912]
 [   13    15  1541  6514     2   872     2     1 94085   933]
 [   14    25  1974  6547     2   857     4     3 94085   865]
 [   15    10  1510  6633     2   884     3     2 94085   918]
 [   17    23  1464  6773     3   965     4     2 94085

In [91]:
sum_price_94085 = data_94085[:,9].sum() #get the sum of all homes with zip

In [92]:
print (data_94085.shape[0])

25


In [93]:
average_94085 = sum_price_94085/25 #get average price
print(average_94085)

885.96


# NumPy Problem 6
### Calculate average price in each zip code: 94085, 94087, 95014, 95051
### Calculate minimum and max price in each zip code: 94085, 94087, 95014, 95051
### Calculate standard deviation of price in each zip code: 94085, 94087, 95014, 95051

In [94]:
# Your code here
housing = np.loadtxt("fixed-housing-data.csv",
                          dtype=int,
                          delimiter=",")
zipcount = {}
for home in housing:
    zipcode = int(home[8])
    home_price = int(home[9])
    if zipcode in zipcount:
        zipcount[zipcode].append(home_price)
    else:
        zipcount[zipcode] = [home_price]

for zipcode in zipcount.keys():
    home_prices = zipcount[zipcode]
    home_average = np.sum(home_prices) //  len(home_prices)
    min_price = np.min(home_prices)
    max_price = np.max(home_prices)
    std_price = np.std(home_prices)
    print(str(zipcode) + "- Average home price: $" + str(home_average) + "K, min: $" + str(min_price ) + "K, max: $" + str(max_price) + "K, Standard Deviation: $" + str(std_price) + "K" )

94085- Average home price: $885K, min: $809K, max: $934K, Standard Deviation: $33.71347505078644K
95051- Average home price: $1023K, min: $942K, max: $1097K, Standard Deviation: $46.03563836855095K
94087- Average home price: $1151K, min: $1103K, max: $1190K, Standard Deviation: $27.56536957851282K
95014- Average home price: $1263K, min: $1194K, max: $1336K, Standard Deviation: $37.73986751434085K


In [95]:
h1 = housing[housing[:,5].argsort()] # by school_api ascending
print(h1)

[[   65    14  1617  8394     2   850     2     0 94087  1138]
 [   73    25  1302  8668     3   850     4     2 95014  1240]
 [   23    15  1828  6956     3   851     4     3 94085   916]
 [   20    13  1358  6819     2   851     3     2 94085   859]
 [   79    17  1373  8953     2   851     2     0 94087  1190]
 [   77    17  1881  8921     3   852     2     0 95014  1194]
 [   19    10  1246  6810     2   853     4     3 95051   942]
 [   32    18  1866  7181     2   854     2     3 95051  1049]
 [   95    13  1582  9339     3   856     3     0 95014  1267]
 [   26    12  1500  7025     2   856     4     2 94085   934]
 [   99    19  1880  9470     3   857     3     3 95014  1269]
 [   53    23  1289  7873     2   857     3     0 95051  1074]
 [   67    24  1947  8502     2   857     4     0 94087  1179]
 [  100    11  1691  9476     4   857     4     0 95014  1250]
 [   14    25  1974  6547     2   857     4     3 94085   865]
 [   44    11  1415  7541     3   859     4     0 95051

In [96]:
h2 = housing[housing[:,5].argsort()[::-1]] # by school_api descending
print(h2)

[[   38    22  1724  7339     3   975     3     3 95051  1038]
 [   35    12  1943  7249     2   974     2     0 95051  1030]
 [   27    13  1836  7027     2   966     3     3 94085   914]
 [   17    23  1464  6773     3   965     4     2 94085   882]
 [   69    21  1575  8579     2   962     4     3 94087  1128]
 [   37    13  1874  7333     3   960     3     2 95051  1044]
 [   45    15  1249  7609     3   960     2     2 95051  1000]
 [    2    10  1563  6085     2   959     4     3 94085   861]
 [    4    14  1215  6129     3   959     4     2 94085   809]
 [   33    11  1953  7199     3   959     3     2 95051  1042]
 [    7    13  1947  6183     3   959     3     1 94085   843]
 [   76    12  1947  8882     3   954     3     2 94087  1173]
 [   59    22  1559  8096     2   953     2     3 95051  1080]
 [   57    11  1927  7983     3   950     3     1 94087  1116]
 [   10    24  1933  6276     2   950     4     1 94085   885]
 [   50    19  1836  7803     3   949     3     0 95051

# NumPy Problem 7
### Find top-2 listings by School API for all zipcodes

In [97]:
# Your code here
api_by_zip = {}
for home in h2:
    home_zip = int(home[8])
    if home_zip not in api_by_zip:        
        api_by_zip[home_zip] = [home]
    elif len(api_by_zip[home_zip]) < 2:
        api_by_zip[home_zip].append(home)

for zipcode in api_by_zip:
    for home in api_by_zip[zipcode]:
        print(str(zipcode) + " - " + str(home) )

95051 - [   38    22  1724  7339     3   975     3     3 95051  1038]
95051 - [   35    12  1943  7249     2   974     2     0 95051  1030]
94085 - [   27    13  1836  7027     2   966     3     3 94085   914]
94085 - [   17    23  1464  6773     3   965     4     2 94085   882]
94087 - [   69    21  1575  8579     2   962     4     3 94087  1128]
94087 - [   76    12  1947  8882     3   954     3     2 94087  1173]
95014 - [   97    10  1645  9352     4   942     3     3 95014  1336]
95014 - [   93    25  1298  9309     3   942     3     0 95014  1269]


# NumPy Problem 8
### Prices are expected to go up by 4% next year.
### Add another column with predicted prices

In [98]:
# Your code here
housing = np.loadtxt("fixed-housing-data.csv",
                          dtype=int,
                          delimiter=",")
housing_count = len(housing)
z = np.zeros((housing_count,1), int)
housing = np.concatenate([housing,z], axis=1)
for i in range(len(housing)):
    home_price = housing[i][9]
    increase = home_price * 1.04
    housing[i][10] = increase
print(housing)

[[    1    24  1757 ... 94085   894   929]
 [    2    10  1563 ... 94085   861   895]
 [    3    14  1344 ... 94085   831   864]
 ...
 [   98    21  1312 ... 95014  1284  1335]
 [   99    19  1880 ... 95014  1269  1319]
 [  100    11  1691 ... 95014  1250  1300]]


# NumPy Problem 9
### Sort the matrix based on HomeID. Save the updated numpy matrix with added column in Problem 8 to a file.

In [99]:
# Your code here
h3 = housing[housing[:,0].argsort()] # by school_api ascending
np.savetxt("fixed-housing-data-with-increase.csv", h3, delimiter=",")


# <font color = magenta> NumPy Problem 10 </font>

Write a function that takes a long string containing multiple words. Print the same string, except with the words in backwards order. 

<i>HINT: Use <b>YOUR_STRING<code>.split()</code></b> function<br></i>

In [100]:
sentence = "This is Lynbrook High school"

backwards_sentence = ' '.join(reversed(sentence.split()))

print(backwards_sentence.capitalize())

School high lynbrook is this
